version: '3'
services:
    web:
        build: .
        env_file:
            - .env
        ports:
            - "8000:8000"
        volumes:
            - ./src/:/app
        command: python manage.py runserver 0.0.0.0:8000
        environment:
            REDIS_HOST: redis
        depends_on:
            - db
            - web_setup

    db:
        image: "postgres:latest"
        hostname: ${POSTGRES_HOST}
        env_file:
            - .env
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    redis:
        image: redis:latest

    web_setup:
        build: .
        env_file:
            - .env
        volumes:
            - ./src/:/app
        command: sh -c "sleep 1 && python manage.py migrate && python manage.py createsuperuser --noinput"
        depends_on:
            - db
volumes:
    db-data:
